name: Assign reviewers based on subdirectory CODEOWNERS

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Assign reviewers
      run: |
        # Set PR number
        PRNUM=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
        echo "PR Number: $PRNUM"

        # Find all the modified files
        FILES=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                     https://api.github.com/repos/${{ github.repository }}/pulls/$PRNUM/files | \
                     jq -r .[].filename)
        
        echo "Modified Files: $FILES"
        
        for FILE in $FILES
        do
          DIRNAME=$(dirname "$FILE")
          echo "Directory: $DIRNAME"
          
          # Look for CODEOWNERS file in the same directory as the changed file
          while [ "$DIRNAME" != "." ]; do
            if [ -f "$DIRNAME/CODEOWNERS" ]; then
              # Extract GitHub username from CODEOWNERS file
              USERS=$(awk -F '[ @]*' '{print $2}' $DIRNAME/CODEOWNERS)
              
              echo "Users: $USERS"
              
              for USER in $USERS
              do
                echo "Requesting review from $USER for PR #$PRNUM."
                gh pr edit $PRNUM --add-reviewer $USER
              done
              break
            fi
            DIRNAME=$(dirname "$DIRNAME")
          done
        done
        if [ ${#USERS[@]} -eq 0 ]; then
          USERS=$(awk -F '[ @]*' '{print $2}' $DIRNAME/CODEOWNERS)
          for USER in $USERS
              do
                echo "Requesting review from $USER for PR #$PRNUM."
                gh pr edit $PRNUM --add-reviewer "$USER"
              done
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
