name: Assign reviewers based on subdirectory CODEOWNERS

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Assign reviewers
      run: |
        # Set PR number
        PRNUM=$(jq --raw-output .number "$GITHUB_EVENT_PATH")

        # Find all the modified files
        FILES=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                     https://api.github.com/repos/${{ github.repository }}/pulls/$PRNUM/files | \
                     jq -r .[].filename)
        
        for FILE in $FILES
        do
          DIRNAME=$(dirname "$FILE")
          # Look for CODEOWNERS file in the same directory as the changed file
          while [ "$DIRNAME" != "." ]; do
            if [ -f "$DIRNAME/CODEOWNERS" ]; then
              # Extract GitHub username from CODEOWNERS file
              USERS=$(awk -F '[ @]*' '{print $2}' $DIRNAME/CODEOWNERS)
              for USER in $USERS
              do
                gh pr review $PRNUM --request $USER
                echo "Requested review from $USER for PR #$PRNUM."
              done
              break
            fi
            DIRNAME=$(dirname "$DIRNAME")
          done
        done
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
